const mongoose = require("mongoose");

// Define the schema for storing user queries and related metadata
const querySchema = new mongoose.Schema({
  user: String,                // The user's name, ID, or identifier
  query: String,               // The actual natural language query submitted by the user
  date: {                      // Timestamp of when the query was submitted
    type: Date,
    default: Date.now,         // Defaults to current time
  },
  decision: String,            // Decision or response generated by the system (e.g., AI output)
  fileName: String,            // Name of the file the query was based on (e.g., uploaded doc/pdf)
});

// Create a Mongoose model from the schema
const Query = mongoose.model("Query", querySchema);

// Export the model to use in other parts of the app
module.exports = Query;
